Feature/processor additions
EveronLife/EveronLife pull request #136
Opened 2022-06-25 11:04 UTC by KasperOnPC

Updated Processor Function with help from @thebonbon 
- Added ability to have multiple inputs
- Added ability to have multiple outputs
- Made it so items that cannot fit in the inventory are instead spawned at the player's feet.

2022-06-25 11:10 UTC, Arkensor commented
> Made it so items that cannot fit in the inventory are instead spawned at the player's feet.

Technically the best solution, the question would be if we should even allow the processing if the player can not store the output amount. I think we could do a pre-check with the player's current volume/weight and have some cached info on the volume and weight of the output prefabs to multiply by how much he will get.

Regardless of checks, I think an error message along the lines of "too full" could be a thing. So we would first try to add the output and if that fails to complete we only remove as much input as needed. We can update the system to do this later and go with spawn on feet for now, but during P1 I would like to get this sorted anyway.

2022-06-25 11:21 UTC, KasperOnPC commented
Yeah, we came to use spawn at feet because the only real current solution was the one where you have to spawn the prefab in the "debug world" to get its entity to get its inventory size. With multiple outputs, this was requiring the spawning of an array of items in the "debug world" which seemed super dodgy.

I agree a dialog box should at least be added that says inventory full when you process and the item is spawned on the ground. I'm happy to be assigned that as an issue for later but would love if this can be merged as-is and that can be added once I / someone else has time to learn about the dialog box prompts and implement it here.

2022-06-25 11:28 UTC, thebonbon requested changes

2022-06-25 11:28 UTC, thebonbon commented on src/Scripts/Game/Features/Processing/EL_ProcessAction.c
> +	ref array<IEntity> foundItems = new array<IEntity>();
```suggestion

```

2022-06-25 11:28 UTC, thebonbon commented on src/Scripts/Game/Features/Processing/EL_ProcessAction.c
> +	private array<IEntity> GetAllInputItems(InventoryStorageManagerComponent inventory, )
```suggestion
	private array<IEntity> GetAllInputItems(InventoryStorageManagerComponent inventory)
```

2022-06-25 11:28 UTC, thebonbon commented on src/Scripts/Game/Features/Processing/EL_ProcessAction.c
> +			foreach (EL_ProcessingInput m_aProcessingInput : m_aProcessingInputs)
```suggestion
			foreach (EL_ProcessingInput processingInput : m_aProcessingInputs)
```

2022-06-25 11:28 UTC, thebonbon commented on src/Scripts/Game/Features/Processing/EL_ProcessAction.c
> +			foreach (EL_ProcessingInput m_aProcessingInput : m_aProcessingInputs)
Not a member var

2022-06-25 11:28 UTC, thebonbon commented on src/Scripts/Game/Features/Processing/EL_ProcessAction.c
> +		foreach (EL_ProcessingInput m_aProcessingInput : m_aProcessingInputs)
```suggestion
		foreach (EL_ProcessingInput processingInput : m_aProcessingInputs) 
```

2022-06-25 11:28 UTC, thebonbon commented on src/Scripts/Game/Features/Processing/EL_ProcessAction.c
> +		bool CanSpawnToStorage = true;
```suggestion
		bool bCanSpawnToStorage = true;
```

2022-06-25 11:28 UTC, thebonbon commented on src/Scripts/Game/Features/Processing/EL_ProcessAction.c
> +		foreach (EL_ProcessingOutput m_aProcessingOutput : m_aProcessingOutputs)
```suggestion
		foreach (EL_ProcessingOutput processingOutput : m_aProcessingOutputs) 
```

2022-06-25 11:28 UTC, thebonbon commented on src/Scripts/Game/Features/Processing/EL_ProcessAction.c
> +					EntitySpawnParams spawnParams = new EntitySpawnParams();
Use `EL_Utils.SpawnEntityPrefab`.. here

2022-06-25 11:28 UTC, thebonbon commented on src/Scripts/Game/Features/Processing/EL_ProcessAction.c
> +		array<string> CannotPerformArray = {};
What is this used for?

2022-06-25 11:28 UTC, thebonbon commented on src/Scripts/Game/Features/Processing/EL_ProcessAction.c
> +		bool CanPerform = true;
```suggestion
		bool bCanPerform = true;
```

2022-06-25 11:28 UTC, thebonbon commented on src/Scripts/Game/Features/Processing/EL_ProcessAction.c
> +		foreach (EL_ProcessingInput m_aProcessingInput : m_aProcessingInputs)
```suggestion
		foreach (EL_ProcessingInput processingInput : m_aProcessingInputs)
```

2022-06-25 12:05 UTC, thebonbon approved these changes

2022-06-25 12:10 UTC, KasperOnPC commented
Updated to meet the script conventions @Arkensor, anything else required?

2022-06-27 11:59 UTC, Arkensor requested changes
Minor formatting changes

2022-06-27 12:14 UTC, Arkensor approved these changes

2022-06-27 12:14 UTC, merged