Fix Processing Input not consuming the last Input
EveronLife/EveronLife pull request #140
Opened 2022-07-02 22:47 UTC by KasperOnPC

Tiny change to fix an issue where the processor was not consuming the last input.

2022-07-03 06:58 UTC, thebonbon approved these changes

2022-07-05 18:20 UTC, Arkensor requested changes
Why does the apple processor take plums now? Maybe that was committed accidently?

2022-07-09 10:04 UTC, KasperOnPC commented
> Why does the apple processor take plums now? Maybe that was committed accidentally?

Yeah it was, fixed now, thanks for flagging that.

2022-07-09 12:49 UTC, Arkensor requested changes
This can be removed.

2022-07-09 12:49 UTC, Arkensor commented on src/Worlds/DebugWorld/DebugWorld_AppleChain.layer
> + }
```suggestion
```

2022-07-09 12:49 UTC, Arkensor commented on src/Scripts/Game/Features/Processing/EL_ProcessAction.c
> +}
```suggestion
}

```

2022-07-09 13:00 UTC, Arkensor approved these changes

2022-07-09 13:00 UTC, merged