Add whitelist system
EveronLife/EveronLife pull request #173
Opened 2022-10-11 18:19 UTC by Thesam1798

### Whitelist System
Hello, I made during the day a whitelist system for the framework.

There are still some features that I would like to add, like the management of the list directly in game and then a permission and role system, which could manage the different sides (medic and cop) or even take the role of license management.

So the whitelist system is a first step for this permission management.

I invite you to read the small documentation I created to understand quickly the system, you can also contact me on discord ; TheSam#0001

PS: there is also a commit to add a generic logger to the whole framework, tell me what you think.

2022-10-11 18:21 UTC, Thesam1798 commented on src/Prefabs/MP/Modes/Roleplay/GameMode_Roleplay.et
> -  }
For information, this was changed when opening the file after a forced save, I did not manage to keep these lines from the editor.

2022-10-11 18:21 UTC, Thesam1798 commented on src/Prefabs/MP/Modes/Roleplay/GameMode_Roleplay.et
> -   }
For information, this was changed when opening the file after a forced save, I did not manage to keep these lines from the editor.

2022-10-12 10:23 UTC, Thesam1798 commented
@thebonbon Done 😊

2022-10-12 11:30 UTC, thebonbon requested changes

2022-10-12 11:30 UTC, thebonbon commented on src/Scripts/Game/Feature/Whitelist/EL_WhitelistComponent.c
> +	private bool m_WhitelistEnable = false;
Bool is default false.
And m_**b**WhitelistEnable

https://github.com/EveronLife/EveronLife/blob/main/.github/CONVENTIONS.md#type-prefixes

2022-10-12 11:46 UTC, Thesam1798 commented on src/Scripts/Game/Feature/Whitelist/EL_WhitelistComponent.c
> +	private bool m_WhitelistEnable = false;
This was not done in many EL files, so I assumed that it did not apply.

In any case it is Fix

2022-10-22 19:05 UTC, Thesam1798 commented
Updated to bring everything up to date with multiplayer.

The logic remains the same, but some security and checks have been added.

Test on a dedicated server on `22/10/2022` with the package `5AACC14F4040793D`, V0.1.0 (https://reforger.armaplatform.com/workshop/5AACC14F4040793D-Fork-Everonlife-Thesam1798)

2022-12-08 08:24 UTC, thebonbon commented
We do need a proper Logger at some point but I'm not sure if we should add a join-whitelist system to the framework. I think this would fit better as a sperarate standalone mod.

2022-12-10 18:41 UTC, Thesam1798 commented
Alright no problem, so you can close the pull request

2022-12-10 18:42 UTC, closed without merging