Addition of Plum Gathering
EveronLife/EveronLife pull request #50
Opened 2022-05-30 12:24 UTC by KasperOnPC

First Contribution to get used to the process/learning.

Context from: 
From: https://github.com/EveronLife/EveronLife/discussions/49

Apologies in advance if there are any issues with this. Play tested and added Plum Tree to Debug Environment for testing.

2022-05-30 12:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/EveronLife/EveronLife?pullRequest=50) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/EveronLife/EveronLife?pullRequest=50) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/EveronLife/EveronLife?pullRequest=50) it.</sub>

2022-05-30 12:39 UTC, alexhosier approved these changes
All tested, working in-game, changes ready to be pulled to main.

2022-05-30 12:45 UTC, Arkensor commented
Hey @KasperOnPC, thank you for your contribution. Before looking at anything else, I must note that the model can not be used. The license (https://blog.turbosquid.com/turbosquid-3d-model-license/#Games-Usage) does not permit free open access and can only be bundled with a closed game binary. To my knowledge, this is not compatible with the MIT license.

The model needs to be swapped out. You can find license complatible models (e.g. CC-BY) here: https://sketchfab.com/search?features=downloadable&licenses=322a749bcfa841b29dff1e8a1bb74b0b&type=models

2022-05-30 12:55 UTC, KasperOnPC commented
That's my bad @Arkensor, thanks for the detailed feedback. It looks like there are some plum models under CC-BY, I will switch it out tomorrow.

Would love any other feedback and appreciate how small a contribution this is. Thanks for all you do.

2022-05-31 11:46 UTC, KasperOnPC commented
Updated with a file with the correct license @Arkensor. I have also ensured the texture and 3D file are super small, 1/100th of the size of the apple.

2022-06-02 10:57 UTC, Arkensor requested changes
- Remove `src/Assets/Items/Food/Plum/Plum.fbx` that should only be in `assets`
- Remove `src/Assets/Items/Food/Plum/Plum.txo` this file is not needed I think. According to the docs, it is just the source of the `xob` binary file. Will be ignored in packing anyway. 
- Some of the paths do not seem to be refreshed and still include `_01`. Not sure how to refresh them. Maybe Rightclick and set no value on the attributes and then select the source again.

2022-06-02 10:57 UTC, Arkensor commented on src/Assets/Items/Food/Plum/Plum.xob.meta
> + Name "{1768DEF76C703B91}Assets/Items/Food/Plum/Plum_01.xob"
This still has the old path in it.

2022-06-02 10:57 UTC, Arkensor commented on src/Assets/Items/Food/Plum/data/Plum.emat.meta
> + Name "{5DCEE3E3833E90FA}Assets/Items/Food/Plum/data/Plum_01.emat"
This still has 01 in the path

2022-06-02 10:57 UTC, Arkensor commented on src/Prefabs/Items/Food/Plum.et
> +   Object "{1768DEF76C703B91}Assets/Items/Food/Plum/Plum_01.xob"
Links to the old xob file

2022-06-02 14:30 UTC, Arkensor commented on src/Assets/Items/Food/Plum/data/Plum.emat.meta
> + Name "{5DCEE3E3833E90FA}Assets/Items/Food/Plum/data/Plum_01.emat"
Still not resolved

2022-06-02 14:33 UTC, Arkensor requested changes
- `src/Assets/Items/Food/Plum/data/Plum.emat.meta` still references `Plum_01.emat`
- Please do not modify other files unrelated to your pull request. Like you did with the apple. Revert that commit for your branch, please.

2022-06-02 21:42 UTC, merged